### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-presentation-team4#11]
See [0228.md](https://github.com/KAIST-IS521/2018-Spring/blob/master/Activities/0228.md).

**Comment by khsdo95** [comment]
Readme.md 의 Abstraction 에서
포스텍 보안 동알리에서 활동을 하고있습니다.
=> 포스텍 보안 동아리에서 활동을 했습니다.
로 바꿔주실 수 있나요?
(오타 및 시점 수정)
