### ISSUE TITLE
Review 1st draft

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-presentation-team4#21]
1st draft를 보고 리뷰.

**Comment by hestati63** [comment]
@khsdo95 
자기 소개 추가해야 할 것 같고 슬라이드 몇개를 빼야할 것 같습니다.

**Comment by hestati63** [comment]
ppt언어: 한글로 통일

**Comment by khsdo95** [comment]
자기소개 - 관심분야 - 개발환경 사진 - 부가적인 설명

**Comment by hestati63** [comment]
금요일 1시에 `IT융합빌딩 508세미나실 (N1 508호)`에서 뵙시다.

**Comment by saykim0727** [comment]
타이틀 통일
- who am i
- research
- environment

애니메이션 추가

image 사이즈 조정
