### ISSUE TITLE
[TA] 발표에 대한 피드백

### ISSUE THREAD

**Issue by mikkang** [KAIST-IS521/2018s-presentation-team4#40]
첫번째 발표에 대한 교수님과 TA들의 피드백을 요약한 것입니다.
다음 발표 때 참고하세요ㅎ

- 발표시간
   - 김희석: 2분 32초
   - 김현기: 1분 22초
   - 정민규: 1분 46초
   - 김홍식: 2분 13초
   - Total(+Intro, Conclusion) : 9분

- 팀
   - 전체적으로 사진보다는 글 위주, 시각화를 위한 사진이나 그래프를  사용하면 더 좋음
   - 자신이 뭘 사용한다에 초점을 맞춘 발표. 자신들을 기억할만한, 어필할수 있는 포인트가 잘 안나타서 아쉬움
   - 특정 발표 슬라이드에 영어 제목 - 한글 내용인 경우가 있음. 슬라이드 내에서 언어의 통일성이 있으면 좋음
   - 제한시간에 비해서 발표를 너무 짧게한 감이 있음, 주어진 시간을 더 살려서 발표를 하면 좋겠음
   - 마지막 슬라이드의 내용이 conclusion으로써 적합한것 같지 않았음. Emacs에 대한 내용은 본인의 희망사항을 이야기 했는데, 그게 왜 사람들로 부터 자신을 어필할수 있는 conclusion인지 잘 모르겠음

- 개인
   - 김희석:  intro를 포함해서 에너지가 넘치는 발표를 해서 좋았음
   - 김현기: 발표 시 좀 더 자신감을 갖고 하면 좋겠음. 본인의 개발 및 연구분야를 더 매력적으로 어필했으면
   - 정민규: 많은 재미있는 셋팅을 하고 있는 점이 잘 표현이 안되어 아쉬움. 발표할 때 목소리도 좀 더 컸으면 좋겠음
   - 김홍식: 슬라이드에 실수가 있었지만(로딩이 느렸던 것인지..), vimrc에 solve.py를 위한 부분이 흥미로웠음

**Comment by sangkilc** [comment]
@mikkang Thank you for creating this issue. I think you'd better put the presentation time for each student in the summary.
