### ISSUE TITLE
Make presentation

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-presentation-team4#42]
어떤 내용을 넣을까요?

**Comment by hestati63** [comment]
Team key의 개인키와 paraphrase를 gpg encryption을 통해 주고받은 내용.

**Comment by khsdo95** [comment]
팀 멤버들의 web of trust를 visualization 한 그림

**Comment by saykim0727** [comment]
오늘 밤까지 팀 전부 sign되면 web of trust사진 /asset에 올릴게요
